### PR TITLE
Adds requirements.txt, pytest.ini (fixing pytest)  updates vide link

### PR DESCRIPTION
**Pull request by khvatov**
Adds missing requirements.txt 
Adds pytest.ini  - needed for pytest to 'see' the source code in 'src' directory
Modifies README.md to update the video link - the original stream had been deleted on twitch and replaced with 'highlights'. The original link no longer worked.

### CODE REVIEW

**Comment by khvatov** [comment]
Just found my old merge request. 'requirements.txt' is not needed; but pytest.ini fixes the issue when 'pytest' cannot see the source code. Probably need to 'cherry-pick' from this merge request.

**Comment by daneah** [comment]
@khvatov thanks for this! Appreciate you finding the new link. Regarding the other files, can you elaborate further on why they're needed? Theoretically everything should be working without them so I want to see how you're running the tests, etc. in case one of us is missing something.

**Comment by khvatov** [comment]
without _pytest.ini_ (I think was added in version 7) you can't just run `pytest` -- it will not find your source in the _src_ directory.
_requirements.txt_ is needed only if you want to run tests and other commands manually. You can, of course run `tox`, but if someone is following your video - then _requirements.txt_ is needed.

**Comment by daneah** [comment]
@khvatov heh, I made need to re-watch my own video 😅 running `tox` is definitely how I typically do things on a regular basis, these days. I'll try to review soon and pull things together accordingly. Thanks again for bringing this up!

**Comment by daneah** [comment]
@khvatov following along freshly with the video, the parts where I use `pytest` directly early on don't require the presence of `pytest.ini`—later parts after moving the code into the `src/` directory do need a pytest configuration so that pytest knows to test against `src/`, but by that point in the video the pytest configuration is moved to `setup.cfg`, which pytest also knows how to use.

Similarly for `requirements.txt`, that is shown early on in the video to show how you might manually install dependencies for a project, but then transitions to using `setup.cfg` and the `install_requires` property in the `options` section to automate that bit.

I'd like to keep this repo representative of the desired end state rather than mixing early demonstration state in, so I'm going to leave off those files for the moment. I will update the link to the video, however! Thanks again for the catch and the opportunity to discuss.

**Pull request closed without merging**
